# Generated by Django 6.0.4 on 2026-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(max_length=255),
        ),
    ]
