# Generated by Django 6.0.4 on 2026-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tools_used', models.CharField(help_text='e.g. Python, Scikit-Learn', max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('notebook_url', models.URLField(blank=True, help_text='Link to Colab/Kaggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
