# Generated by Django 6.0.4 on 2026-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='notebook_url',
            field=models.URLField(blank=True),
        ),
    ]
